[package]
name = "spam_or_ham"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.10.0-alpha.2", features = ["blocking"] }
rustlearn = "0.5.0"
tempfile = "3.12.0"
time = "0.3.36"
zip = "2.1.6"
